"""
dbt Generator
Generates dbt model files and schema YAML from the data product definition.
"""

import yaml


class DbtGenerator:
    """Produces dbt model SQL and schema YAML from the data product definition."""

    def __init__(self, product: dict):
        self.product = product

    def generate_schema_yaml(self) -> str:
        """Generate a dbt schema.yml file from the data model."""
        entities = self.product.get("entities", [])

        models = []
        for entity in entities:
            columns = []
            for attr in entity.get("attributes", []):
                col_def = {
                    "name": attr["name"],
                    "description": attr.get("description", ""),
                }
                tests = []
                if not attr.get("nullable", True):
                    tests.append("not_null")
                if attr.get("pii"):
                    col_def["meta"] = {"pii": True}
                if tests:
                    col_def["tests"] = tests
                columns.append(col_def)

            models.append({
                "name": entity["name"],
                "description": f"Entity: {entity['name']}",
                "columns": columns,
            })

        schema = {"version": 2, "models": models}
        return yaml.dump(schema, default_flow_style=False, sort_keys=False)

    def generate_model_sql(self, entity: dict) -> str:
        """Generate a dbt model SQL file for an entity."""
        name = entity.get("name", "unnamed")
        attributes = entity.get("attributes", [])
        col_list = ",\n    ".join(a["name"] for a in attributes) if attributes else "*"

        return (
            f"-- dbt model for {name}\n"
            f"-- Generated by GDP Data Product Steward\n\n"
            f"SELECT\n    {col_list}\n"
            f"FROM {{{{ source('{name.lower()}_source', '{name.lower()}') }}}}\n"
        )

    def generate_all_models(self) -> dict:
        """Return a dict of filename -> SQL content for all entities."""
        entities = self.product.get("entities", [])
        return {
            f"{ent['name'].lower()}.sql": self.generate_model_sql(ent)
            for ent in entities
        }
