"""
Snowflake Generator
Generates DDL, masking policies, secure views, and grants from the product definition.
"""


class SnowflakeGenerator:
    """Produces Snowflake-compatible DDL from the data product definition."""

    def __init__(self, product: dict):
        self.product = product

    def generate_ddl(self) -> str:
        """Generate CREATE TABLE statements for all entities."""
        entities = self.product.get("entities", [])
        if not entities:
            return "-- No entities defined."

        statements = []
        for entity in entities:
            statements.append(self._create_table(entity))
        return "\n\n".join(statements)

    def _create_table(self, entity: dict) -> str:
        """Generate a single CREATE TABLE statement."""
        name = entity.get("name", "UNNAMED")
        attributes = entity.get("attributes", [])

        col_defs = []
        for attr in attributes:
            col_name = attr.get("name", "UNNAMED")
            col_type = attr.get("data_type", "VARCHAR")
            nullable = "NULL" if attr.get("nullable", True) else "NOT NULL"
            comment = f" COMMENT '{attr.get('description', '')}'" if attr.get("description") else ""
            col_defs.append(f"    {col_name} {col_type} {nullable}{comment}")

        cols_sql = ",\n".join(col_defs) if col_defs else "    -- no columns defined"

        return (
            f"-- Generated by GDP Data Product Steward\n"
            f"CREATE TABLE IF NOT EXISTS {name} (\n{cols_sql}\n);"
        )

    def generate_masking_policies(self) -> str:
        """Generate masking policies for PII attributes."""
        if not self.product.get("pii"):
            return "-- No PII detected. No masking policies required."

        policies = ["-- Masking Policies for PII Attributes\n"]

        for entity in self.product.get("entities", []):
            for attr in entity.get("attributes", []):
                if attr.get("pii"):
                    policy_name = f"MASK_{entity['name']}_{attr['name']}"
                    dtype = attr.get("data_type", "STRING")
                    policies.append(
                        f"CREATE OR REPLACE MASKING POLICY {policy_name}\n"
                        f"  AS (val {dtype})\n"
                        f"  RETURNS {dtype} ->\n"
                        f"  CASE\n"
                        f"    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER', 'DATA_OWNER') THEN val\n"
                        f"    ELSE '***MASKED***'\n"
                        f"  END;\n"
                    )
                    policies.append(
                        f"ALTER TABLE {entity['name']} ALTER COLUMN {attr['name']} "
                        f"SET MASKING POLICY {policy_name};\n"
                    )

        return "\n".join(policies)

    def generate_secure_views(self) -> str:
        """Generate secure views if classification is Restricted."""
        classification = self.product.get("classification", "")
        if classification not in ("Restricted", "Confidential"):
            return "-- Classification does not require secure views."

        views = [f"-- Secure Views ({classification} classification)\n"]

        for entity in self.product.get("entities", []):
            name = entity["name"]
            attrs = entity.get("attributes", [])
            col_list = ", ".join(a["name"] for a in attrs) if attrs else "*"

            views.append(
                f"CREATE OR REPLACE SECURE VIEW V_{name} AS\n"
                f"SELECT\n    {col_list}\n"
                f"FROM {name};\n"
            )

        return "\n".join(views)

    def generate_grants(self) -> str:
        """Generate GRANT statements based on access roles."""
        roles_raw = self.product.get("access_roles", "")
        if not roles_raw:
            return "-- No access roles defined."

        roles = [r.strip() for r in roles_raw.split(",") if r.strip()]
        entities = self.product.get("entities", [])

        grants = ["-- Access Grants\n"]
        for entity in entities:
            table = entity.get("name", "UNNAMED")
            for role in roles:
                grants.append(f"GRANT SELECT ON TABLE {table} TO ROLE {role};")

        return "\n".join(grants)

    def generate_all(self) -> str:
        """Generate complete Snowflake deployment script."""
        sections = [
            self.generate_ddl(),
            self.generate_masking_policies(),
            self.generate_secure_views(),
            self.generate_grants(),
        ]
        return "\n\n-- " + "=" * 60 + "\n\n".join(sections)
