"""
dbt Generator
Generates dbt model files and schema YAML from the data product definition.
"""

import yaml


class DbtGenerator:
    """Produces dbt model SQL and schema YAML from the data product definition."""

    def __init__(self, state_snapshot: dict):
        self.state = state_snapshot

    def generate_schema_yaml(self) -> str:
        """Generate a dbt schema.yml file from the data model."""
        model = self.state.get("data_model", {})
        entities = model.get("entities", [])
        dq = self.state.get("data_quality", {})

        models = []
        for entity in entities:
            columns = []
            for col in entity.get("columns", []):
                col_def = {"name": col["name"]}
                if col["name"] == entity.get("primary_key"):
                    col_def["tests"] = ["unique", "not_null"]
                columns.append(col_def)

            models.append({
                "name": entity["name"],
                "description": entity.get("description", ""),
                "columns": columns,
            })

        schema = {"version": 2, "models": models}
        return yaml.dump(schema, default_flow_style=False, sort_keys=False)

    def generate_model_sql(self, entity: dict) -> str:
        """Generate a basic dbt model SQL file for an entity."""
        name = entity.get("name", "unnamed")
        columns = entity.get("columns", [])
        col_list = ", ".join(c["name"] for c in columns) if columns else "*"

        return (
            f"-- dbt model for {name}\n"
            f"-- Generated by Data Product Builder\n\n"
            f"SELECT\n    {col_list}\n"
            f"FROM {{{{ source('{name}_source', '{name}') }}}}\n"
        )

    def generate_all_models(self) -> dict:
        """Return a dict of filename -> SQL content for all entities."""
        model = self.state.get("data_model", {})
        entities = model.get("entities", [])
        return {
            f"{ent['name']}.sql": self.generate_model_sql(ent)
            for ent in entities
        }
